### ISSUE TITLE
Cannot find the file /analytics/plugins/JsTrackerCustom/tracker.js 

### ISSUE THREAD

**Issue by Chardonneaur** [innocraft/plugin-JsTrackerCustom#22]
Hi guys,
There is no file tracker.js within JsTrackerCustom only .php files.

**Comment by AltamashShaikh** [comment]
@Chardonneaur there will be no `tracker.js` file included since its already git ignored - https://github.com/innocraft/plugin-JsTrackerCustom/blob/4.x-dev/.gitignore#L1
We also found that people needs to create `tracker.js` in order to use this even though the plugin directory is writable.
Will propose a fix to create the file if directory is writable and file does not exist

**Comment by AltamashShaikh** [comment]
Hey @Chardonneaur Added code to autocreate `tracker.js` if proper permissions are present, we should release the new version of plugin in coming days.

**Comment by Chardonneaur** [comment]
That's awesome @AltamashShaikh thank you, because, as I am writing the book about Matomo and that I am talking about all plugins I was stucked with this one.
